# Generated by Django 3.1.4 on 2021-04-04 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_mycourses'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyCourses',
        ),
    ]
